image: maven:3.6.3-jdk-8

variables:
  PREFIX: slack-api-test
  TAGS: regression

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean verify -Dcucumber.filter.tags=@$TAGS

  after_script:
    - apt-get update
    - apt-get install -y zip unzip
    - zip -r serenity_report.zip ./target/site/serenity

  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ./serenity_report.zip